# Generated by Django 5.1.3 on 2024-11-05 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ElementoTabelaPeriodica',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('simbolo', models.CharField(max_length=5)),
                ('numero_atomico', models.IntegerField()),
                ('nome', models.CharField(max_length=100)),
                ('massa_atomica', models.DecimalField(decimal_places=5, max_digits=10)),
                ('propriedades', models.TextField(blank=True, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
